# REGISTER (user)
POST http://localhost:3000/users
Content-Type: application/json

{
    "nama": "admin",
    "email": "email2@gmail.com",
    "password": "password123",
    "confPassword": "password123"
}

# LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}

# UPDATE
PATCH http://localhost:3000/users/0bb1a972-755d-434f-8f6a-9d0971d11940
Content-Type: application/json

{
    "nama": "admin",
    "alamat": "jl. abdul wahab",
    "email": "admin2@gmail.com",
    "no_telp": "087700345684",
    "jml_point": 10
}

# GET USERS
GET http://localhost:3000/users

# GET USER BY ID
GET http://localhost:3000/users/0bb1a972-755d-434f-8f6a-9d0971d11940

# DELETE USER BY ID
DELETE http://localhost:3000/users/22fb411a-a76f-4af6-aaf8-09c63e149e0e